PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

CREATE TABLE CLASSES (
    ID        INTEGER       PRIMARY KEY AUTOINCREMENT
                            NOT NULL,
    CLASSNAME  VARCHAR (255),
    LANGUAGE_ID INTEGER,
    LEVEL_ID INTEGER,
    TEACHERLEVEL_ID INTEGER,
    PRICE INTEGER
);

CREATE TABLE LANGUAGES (
    ID        INTEGER       PRIMARY KEY AUTOINCREMENT
                            NOT NULL,
    LANGUAGE  VARCHAR (255)    
);
INSERT INTO LANGUAGES (ID, LANGUAGE) VALUES (1, 'Португальский');
INSERT INTO LANGUAGES (ID, LANGUAGE) VALUES (2, 'Испанский');
INSERT INTO LANGUAGES (ID, LANGUAGE) VALUES (3, 'Английский');
INSERT INTO LANGUAGES (ID, LANGUAGE) VALUES (4, 'Французский');
INSERT INTO LANGUAGES (ID, LANGUAGE) VALUES (5, 'Немецкий');
INSERT INTO LANGUAGES (ID, LANGUAGE) VALUES (6, 'Итальянский');

CREATE TABLE LEVELS (
    ID        INTEGER       PRIMARY KEY AUTOINCREMENT
                            NOT NULL,
    LEVELNAME  VARCHAR (255)    
);
INSERT INTO LEVELS (ID, LEVELNAME) VALUES (1, 'advanced');
INSERT INTO LEVELS (ID, LEVELNAME) VALUES (2, 'begginer');
INSERT INTO LEVELS (ID, LEVELNAME) VALUES (3, 'intermediate');

CREATE TABLE RESERVES (
    ID        INTEGER       PRIMARY KEY AUTOINCREMENT
                            NOT NULL,
    STUDENT_ID  INTEGER,
    CLASS_ID  INTEGER,
    PRICE INTEGER,
    KURSCOUNT INTEGER,
    STARTDATE DATE
);


CREATE TABLE STUDENTS (
    ID        INTEGER       PRIMARY KEY AUTOINCREMENT
                            NOT NULL,
    SFAMILY VARCHAR (255),
    SNAME VARCHAR (255),
    SPARENT VARCHAR (255),
    DOCUMENT VARCHAR (255),
    PHONE VARCHAR (255)
);


CREATE TABLE TEACHERLEVELS (
    ID        INTEGER       PRIMARY KEY AUTOINCREMENT
                            NOT NULL,
    LEVELNAME  VARCHAR (255)    
);
INSERT INTO TEACHERLEVELS (ID, LEVELNAME) VALUES (1, 'Expert');
INSERT INTO TEACHERLEVELS (ID, LEVELNAME) VALUES (2, 'Proficient');
INSERT INTO TEACHERLEVELS (ID, LEVELNAME) VALUES (3, 'Developing');
INSERT INTO TEACHERLEVELS (ID, LEVELNAME) VALUES (4, 'Foundation');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
